apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: istvanapp1
  name: istvanapp1
  namespace: istvan-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istvanapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: istvanapp1
    spec:
      containers:
      - image: blotunga/istvanmobi:appv1
        name: istvanmobi
        ports:
        - containerPort: 80
        resources: {}
status: {}
# adding service with nodeport
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: istvansvc1
  name: istvansvc1
  namespace: istvan-project
spec:
  ports:
  - name: 1215-80
    port: 1215
    protocol: TCP
    targetPort: 80
  selector: #need to match label of pods
    app: istvanapp1
  type: NodePort
status:
  loadBalancer: {}
